import localFont from "next/font/local";
// import "../globals.css";

import SessionWrapper from "../components/SessionWrapper";
import Navbar from "../components/Navbar";
import { Suspense } from "react";
import Loading from "../components/Loading";


// const geistSans = localFont({
//     src: "../fonts/GeistVF.woff",
//     variable: "--font-geist-sans",
//     weight: "100 900",
// });
// const geistMono = localFont({
//     src: "../fonts/GeistMonoVF.woff",
//     variable: "--font-geist-mono",
//     weight: "100 900",
// });

export const metadata = {
    title: "Student - AJU-BTS",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (

        <SessionWrapper>
            <Navbar />
            <Suspense fallback={<Loading/>}>
            <main className='relative  pt-14  border-t-2 sm:border-t-0 h-[calc(100vh)] bg-white dark:bg-black text-black dark:text-white'>
                {children}
            </main>
            </Suspense>

        </SessionWrapper>


    );
}
